// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAlert = `-- name: CreateAlert :one

INSERT INTO alerts (parcel_id, alert_type, severity, message)
VALUES ($1, $2, $3, $4)
RETURNING id, parcel_id, alert_type, severity, message, resolved, created_at
`

type CreateAlertParams struct {
	ParcelID  int64  `json:"parcel_id"`
	AlertType string `json:"alert_type"`
	Severity  string `json:"severity"`
	Message   string `json:"message"`
}

type CreateAlertRow struct {
	ID        int64              `json:"id"`
	ParcelID  int64              `json:"parcel_id"`
	AlertType string             `json:"alert_type"`
	Severity  string             `json:"severity"`
	Message   string             `json:"message"`
	Resolved  bool               `json:"resolved"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Alert queries
func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (CreateAlertRow, error) {
	row := q.db.QueryRow(ctx, createAlert,
		arg.ParcelID,
		arg.AlertType,
		arg.Severity,
		arg.Message,
	)
	var i CreateAlertRow
	err := row.Scan(
		&i.ID,
		&i.ParcelID,
		&i.AlertType,
		&i.Severity,
		&i.Message,
		&i.Resolved,
		&i.CreatedAt,
	)
	return i, err
}

const getAlert = `-- name: GetAlert :one
SELECT id, parcel_id, alert_type, severity, message, resolved, created_at
FROM alerts WHERE id = $1
`

type GetAlertRow struct {
	ID        int64              `json:"id"`
	ParcelID  int64              `json:"parcel_id"`
	AlertType string             `json:"alert_type"`
	Severity  string             `json:"severity"`
	Message   string             `json:"message"`
	Resolved  bool               `json:"resolved"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAlert(ctx context.Context, id int64) (GetAlertRow, error) {
	row := q.db.QueryRow(ctx, getAlert, id)
	var i GetAlertRow
	err := row.Scan(
		&i.ID,
		&i.ParcelID,
		&i.AlertType,
		&i.Severity,
		&i.Message,
		&i.Resolved,
		&i.CreatedAt,
	)
	return i, err
}

const listAlerts = `-- name: ListAlerts :many
SELECT id, parcel_id, alert_type, severity, message, resolved, created_at
FROM alerts WHERE parcel_id = $1 AND severity = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListAlertsParams struct {
	ParcelID int64  `json:"parcel_id"`
	Severity string `json:"severity"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

type ListAlertsRow struct {
	ID        int64              `json:"id"`
	ParcelID  int64              `json:"parcel_id"`
	AlertType string             `json:"alert_type"`
	Severity  string             `json:"severity"`
	Message   string             `json:"message"`
	Resolved  bool               `json:"resolved"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAlerts(ctx context.Context, arg ListAlertsParams) ([]ListAlertsRow, error) {
	rows, err := q.db.Query(ctx, listAlerts,
		arg.ParcelID,
		arg.Severity,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlertsRow
	for rows.Next() {
		var i ListAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParcelID,
			&i.AlertType,
			&i.Severity,
			&i.Message,
			&i.Resolved,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAlert = `-- name: ResolveAlert :exec
UPDATE alerts
SET resolved = TRUE, resolved_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) ResolveAlert(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, resolveAlert, id)
	return err
}
