// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID         int64              `json:"id"`
	ParcelID   int64              `json:"parcel_id"`
	AlertType  string             `json:"alert_type"`
	Severity   string             `json:"severity"`
	Message    string             `json:"message"`
	Resolved   bool               `json:"resolved"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
}
