// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	// Alert queries
	CreateAlert(ctx context.Context, arg CreateAlertParams) (CreateAlertRow, error)
	GetAlert(ctx context.Context, id int64) (GetAlertRow, error)
	ListAlerts(ctx context.Context, arg ListAlertsParams) ([]ListAlertsRow, error)
	ResolveAlert(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
