// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: producers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProducer = `-- name: CreateProducer :one

INSERT INTO producers (user_id, name, document_id, phone, email, address)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, document_id, phone, email, address, created_at
`

type CreateProducerParams struct {
	UserID     int64       `json:"user_id"`
	Name       string      `json:"name"`
	DocumentID string      `json:"document_id"`
	Phone      pgtype.Text `json:"phone"`
	Email      pgtype.Text `json:"email"`
	Address    pgtype.Text `json:"address"`
}

type CreateProducerRow struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	Name       string             `json:"name"`
	DocumentID string             `json:"document_id"`
	Phone      pgtype.Text        `json:"phone"`
	Email      pgtype.Text        `json:"email"`
	Address    pgtype.Text        `json:"address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// Producer queries
func (q *Queries) CreateProducer(ctx context.Context, arg CreateProducerParams) (CreateProducerRow, error) {
	row := q.db.QueryRow(ctx, createProducer,
		arg.UserID,
		arg.Name,
		arg.DocumentID,
		arg.Phone,
		arg.Email,
		arg.Address,
	)
	var i CreateProducerRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DocumentID,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProducer = `-- name: DeleteProducer :exec
DELETE FROM producers WHERE id = $1
`

func (q *Queries) DeleteProducer(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProducer, id)
	return err
}

const getProducer = `-- name: GetProducer :one
SELECT id, user_id, name, document_id, phone, email, address, created_at
FROM producers WHERE id = $1
`

type GetProducerRow struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	Name       string             `json:"name"`
	DocumentID string             `json:"document_id"`
	Phone      pgtype.Text        `json:"phone"`
	Email      pgtype.Text        `json:"email"`
	Address    pgtype.Text        `json:"address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetProducer(ctx context.Context, id int64) (GetProducerRow, error) {
	row := q.db.QueryRow(ctx, getProducer, id)
	var i GetProducerRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DocumentID,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.CreatedAt,
	)
	return i, err
}

const getProducerCount = `-- name: GetProducerCount :one
SELECT COUNT(*) FROM producers WHERE user_id = $1
`

func (q *Queries) GetProducerCount(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getProducerCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listProducers = `-- name: ListProducers :many
SELECT id, user_id, name, document_id, phone, email, address, created_at
FROM producers WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProducersParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListProducersRow struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	Name       string             `json:"name"`
	DocumentID string             `json:"document_id"`
	Phone      pgtype.Text        `json:"phone"`
	Email      pgtype.Text        `json:"email"`
	Address    pgtype.Text        `json:"address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListProducers(ctx context.Context, arg ListProducersParams) ([]ListProducersRow, error) {
	rows, err := q.db.Query(ctx, listProducers, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProducersRow
	for rows.Next() {
		var i ListProducersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.DocumentID,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProducer = `-- name: UpdateProducer :exec
UPDATE producers
SET name = $2, phone = $3, email = $4, address = $5, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateProducerParams struct {
	ID      int64       `json:"id"`
	Name    string      `json:"name"`
	Phone   pgtype.Text `json:"phone"`
	Email   pgtype.Text `json:"email"`
	Address pgtype.Text `json:"address"`
}

func (q *Queries) UpdateProducer(ctx context.Context, arg UpdateProducerParams) error {
	_, err := q.db.Exec(ctx, updateProducer,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Address,
	)
	return err
}
