// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	// Producer queries
	CreateProducer(ctx context.Context, arg CreateProducerParams) (CreateProducerRow, error)
	DeleteProducer(ctx context.Context, id int64) error
	GetProducer(ctx context.Context, id int64) (GetProducerRow, error)
	GetProducerCount(ctx context.Context, userID int64) (int64, error)
	ListProducers(ctx context.Context, arg ListProducersParams) ([]ListProducersRow, error)
	UpdateProducer(ctx context.Context, arg UpdateProducerParams) error
}

var _ Querier = (*Queries)(nil)
