// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v6.33.5
// source: parcel.proto

package parcel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateParcelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProducerId   int64   `protobuf:"varint,1,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	Name         string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description  string  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	GeometryWkt  string  `protobuf:"bytes,4,opt,name=geometry_wkt,json=geometryWkt,proto3" json:"geometry_wkt,omitempty"`
	AreaHectares float64 `protobuf:"fixed64,5,opt,name=area_hectares,json=areaHectares,proto3" json:"area_hectares,omitempty"`
	CropType     string  `protobuf:"bytes,6,opt,name=crop_type,json=cropType,proto3" json:"crop_type,omitempty"`
}

func (x *CreateParcelRequest) Reset() {
	*x = CreateParcelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateParcelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateParcelRequest) ProtoMessage() {}

func (x *CreateParcelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateParcelRequest.ProtoReflect.Descriptor instead.
func (*CreateParcelRequest) Descriptor() ([]byte, []int) {
	return file_parcel_proto_rawDescGZIP(), []int{0}
}

func (x *CreateParcelRequest) GetProducerId() int64 {
	if x != nil {
		return x.ProducerId
	}
	return 0
}

func (x *CreateParcelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateParcelRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateParcelRequest) GetGeometryWkt() string {
	if x != nil {
		return x.GeometryWkt
	}
	return ""
}

func (x *CreateParcelRequest) GetAreaHectares() float64 {
	if x != nil {
		return x.AreaHectares
	}
	return 0
}

func (x *CreateParcelRequest) GetCropType() string {
	if x != nil {
		return x.CropType
	}
	return ""
}

type CreateParcelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParcelId int64  `protobuf:"varint,1,opt,name=parcel_id,json=parcelId,proto3" json:"parcel_id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Message  string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateParcelResponse) Reset() {
	*x = CreateParcelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateParcelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateParcelResponse) ProtoMessage() {}

func (x *CreateParcelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateParcelResponse.ProtoReflect.Descriptor instead.
func (*CreateParcelResponse) Descriptor() ([]byte, []int) {
	return file_parcel_proto_rawDescGZIP(), []int{1}
}

func (x *CreateParcelResponse) GetParcelId() int64 {
	if x != nil {
		return x.ParcelId
	}
	return 0
}

func (x *CreateParcelResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateParcelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetParcelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParcelId int64 `protobuf:"varint,1,opt,name=parcel_id,json=parcelId,proto3" json:"parcel_id,omitempty"`
}

func (x *GetParcelRequest) Reset() {
	*x = GetParcelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetParcelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParcelRequest) ProtoMessage() {}

func (x *GetParcelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParcelRequest.ProtoReflect.Descriptor instead.
func (*GetParcelRequest) Descriptor() ([]byte, []int) {
	return file_parcel_proto_rawDescGZIP(), []int{2}
}

func (x *GetParcelRequest) GetParcelId() int64 {
	if x != nil {
		return x.ParcelId
	}
	return 0
}

type GetParcelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParcelId     int64   `protobuf:"varint,1,opt,name=parcel_id,json=parcelId,proto3" json:"parcel_id,omitempty"`
	ProducerId   int64   `protobuf:"varint,2,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	Name         string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description  string  `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	GeometryWkt  string  `protobuf:"bytes,5,opt,name=geometry_wkt,json=geometryWkt,proto3" json:"geometry_wkt,omitempty"`
	AreaHectares float64 `protobuf:"fixed64,6,opt,name=area_hectares,json=areaHectares,proto3" json:"area_hectares,omitempty"`
	CropType     string  `protobuf:"bytes,7,opt,name=crop_type,json=cropType,proto3" json:"crop_type,omitempty"`
	CreatedAt    int64   `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *GetParcelResponse) Reset() {
	*x = GetParcelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetParcelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParcelResponse) ProtoMessage() {}

func (x *GetParcelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParcelResponse.ProtoReflect.Descriptor instead.
func (*GetParcelResponse) Descriptor() ([]byte, []int) {
	return file_parcel_proto_rawDescGZIP(), []int{3}
}

func (x *GetParcelResponse) GetParcelId() int64 {
	if x != nil {
		return x.ParcelId
	}
	return 0
}

func (x *GetParcelResponse) GetProducerId() int64 {
	if x != nil {
		return x.ProducerId
	}
	return 0
}

func (x *GetParcelResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetParcelResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetParcelResponse) GetGeometryWkt() string {
	if x != nil {
		return x.GeometryWkt
	}
	return ""
}

func (x *GetParcelResponse) GetAreaHectares() float64 {
	if x != nil {
		return x.AreaHectares
	}
	return 0
}

func (x *GetParcelResponse) GetCropType() string {
	if x != nil {
		return x.CropType
	}
	return ""
}

func (x *GetParcelResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListParcelsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProducerId int64 `protobuf:"varint,1,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	Limit      int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset     int32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListParcelsRequest) Reset() {
	*x = ListParcelsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListParcelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListParcelsRequest) ProtoMessage() {}

func (x *ListParcelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListParcelsRequest.ProtoReflect.Descriptor instead.
func (*ListParcelsRequest) Descriptor() ([]byte, []int) {
	return file_parcel_proto_rawDescGZIP(), []int{4}
}

func (x *ListParcelsRequest) GetProducerId() int64 {
	if x != nil {
		return x.ProducerId
	}
	return 0
}

func (x *ListParcelsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListParcelsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListParcelsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parcels []*GetParcelResponse `protobuf:"bytes,1,rep,name=parcels,proto3" json:"parcels,omitempty"`
	Total   int32                `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ListParcelsResponse) Reset() {
	*x = ListParcelsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListParcelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListParcelsResponse) ProtoMessage() {}

func (x *ListParcelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListParcelsResponse.ProtoReflect.Descriptor instead.
func (*ListParcelsResponse) Descriptor() ([]byte, []int) {
	return file_parcel_proto_rawDescGZIP(), []int{5}
}

func (x *ListParcelsResponse) GetParcels() []*GetParcelResponse {
	if x != nil {
		return x.Parcels
	}
	return nil
}

func (x *ListParcelsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateParcelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParcelId    int64  `protobuf:"varint,1,opt,name=parcel_id,json=parcelId,proto3" json:"parcel_id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CropType    string `protobuf:"bytes,4,opt,name=crop_type,json=cropType,proto3" json:"crop_type,omitempty"`
	GeometryWkt string `protobuf:"bytes,5,opt,name=geometry_wkt,json=geometryWkt,proto3" json:"geometry_wkt,omitempty"`
}

func (x *UpdateParcelRequest) Reset() {
	*x = UpdateParcelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateParcelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateParcelRequest) ProtoMessage() {}

func (x *UpdateParcelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateParcelRequest.ProtoReflect.Descriptor instead.
func (*UpdateParcelRequest) Descriptor() ([]byte, []int) {
	return file_parcel_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateParcelRequest) GetParcelId() int64 {
	if x != nil {
		return x.ParcelId
	}
	return 0
}

func (x *UpdateParcelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateParcelRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateParcelRequest) GetCropType() string {
	if x != nil {
		return x.CropType
	}
	return ""
}

func (x *UpdateParcelRequest) GetGeometryWkt() string {
	if x != nil {
		return x.GeometryWkt
	}
	return ""
}

type UpdateParcelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParcelId int64  `protobuf:"varint,1,opt,name=parcel_id,json=parcelId,proto3" json:"parcel_id,omitempty"`
	Message  string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdateParcelResponse) Reset() {
	*x = UpdateParcelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateParcelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateParcelResponse) ProtoMessage() {}

func (x *UpdateParcelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateParcelResponse.ProtoReflect.Descriptor instead.
func (*UpdateParcelResponse) Descriptor() ([]byte, []int) {
	return file_parcel_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateParcelResponse) GetParcelId() int64 {
	if x != nil {
		return x.ParcelId
	}
	return 0
}

func (x *UpdateParcelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteParcelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParcelId int64 `protobuf:"varint,1,opt,name=parcel_id,json=parcelId,proto3" json:"parcel_id,omitempty"`
}

func (x *DeleteParcelRequest) Reset() {
	*x = DeleteParcelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteParcelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteParcelRequest) ProtoMessage() {}

func (x *DeleteParcelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteParcelRequest.ProtoReflect.Descriptor instead.
func (*DeleteParcelRequest) Descriptor() ([]byte, []int) {
	return file_parcel_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteParcelRequest) GetParcelId() int64 {
	if x != nil {
		return x.ParcelId
	}
	return 0
}

type DeleteParcelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteParcelResponse) Reset() {
	*x = DeleteParcelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteParcelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteParcelResponse) ProtoMessage() {}

func (x *DeleteParcelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteParcelResponse.ProtoReflect.Descriptor instead.
func (*DeleteParcelResponse) Descriptor() ([]byte, []int) {
	return file_parcel_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteParcelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteParcelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type QueryByGeometryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GeometryWkt string `protobuf:"bytes,1,opt,name=geometry_wkt,json=geometryWkt,proto3" json:"geometry_wkt,omitempty"`
	QueryType   string `protobuf:"bytes,2,opt,name=query_type,json=queryType,proto3" json:"query_type,omitempty"`
}

func (x *QueryByGeometryRequest) Reset() {
	*x = QueryByGeometryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryByGeometryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryByGeometryRequest) ProtoMessage() {}

func (x *QueryByGeometryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryByGeometryRequest.ProtoReflect.Descriptor instead.
func (*QueryByGeometryRequest) Descriptor() ([]byte, []int) {
	return file_parcel_proto_rawDescGZIP(), []int{10}
}

func (x *QueryByGeometryRequest) GetGeometryWkt() string {
	if x != nil {
		return x.GeometryWkt
	}
	return ""
}

func (x *QueryByGeometryRequest) GetQueryType() string {
	if x != nil {
		return x.QueryType
	}
	return ""
}

type QueryByGeometryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parcels []*GetParcelResponse `protobuf:"bytes,1,rep,name=parcels,proto3" json:"parcels,omitempty"`
	Total   int32                `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *QueryByGeometryResponse) Reset() {
	*x = QueryByGeometryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parcel_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryByGeometryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryByGeometryResponse) ProtoMessage() {}

func (x *QueryByGeometryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryByGeometryResponse.ProtoReflect.Descriptor instead.
func (*QueryByGeometryResponse) Descriptor() ([]byte, []int) {
	return file_parcel_proto_rawDescGZIP(), []int{11}
}

func (x *QueryByGeometryResponse) GetParcels() []*GetParcelResponse {
	if x != nil {
		return x.Parcels
	}
	return nil
}

func (x *QueryByGeometryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_parcel_proto protoreflect.FileDescriptor

var file_parcel_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x22, 0xd1, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72,
	0x79, 0x5f, 0x77, 0x6b, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x65, 0x6f,
	0x6d, 0x65, 0x74, 0x72, 0x79, 0x57, 0x6b, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x72, 0x65, 0x61,
	0x5f, 0x68, 0x65, 0x63, 0x74, 0x61, 0x72, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0c, 0x61, 0x72, 0x65, 0x61, 0x48, 0x65, 0x63, 0x74, 0x61, 0x72, 0x65, 0x73, 0x12, 0x1b, 0x0a,
	0x09, 0x63, 0x72, 0x6f, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x72, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x22, 0x61, 0x0a, 0x14, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2f, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x49, 0x64, 0x22, 0x8b,
	0x02, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x49,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x67, 0x65, 0x6f, 0x6d,
	0x65, 0x74, 0x72, 0x79, 0x5f, 0x77, 0x6b, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x57, 0x6b, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x61,
	0x72, 0x65, 0x61, 0x5f, 0x68, 0x65, 0x63, 0x74, 0x61, 0x72, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0c, 0x61, 0x72, 0x65, 0x61, 0x48, 0x65, 0x63, 0x74, 0x61, 0x72, 0x65, 0x73,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x72, 0x6f, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x63, 0x0a, 0x12,
	0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x22, 0x60, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x07, 0x70, 0x61, 0x72, 0x63,
	0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x61, 0x72, 0x63,
	0x65, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x07, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x22, 0xa8, 0x01, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61,
	0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x61, 0x72, 0x63, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b,
	0x0a, 0x09, 0x63, 0x72, 0x6f, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x72, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x67,
	0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x77, 0x6b, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x57, 0x6b, 0x74, 0x22, 0x4d,
	0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x72, 0x63, 0x65,
	0x6c, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x32, 0x0a,
	0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x49,
	0x64, 0x22, 0x4a, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x5a, 0x0a,
	0x16, 0x51, 0x75, 0x65, 0x72, 0x79, 0x42, 0x79, 0x47, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x67, 0x65, 0x6f, 0x6d, 0x65,
	0x74, 0x72, 0x79, 0x5f, 0x77, 0x6b, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67,
	0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x57, 0x6b, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x22, 0x64, 0x0a, 0x17, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x42, 0x79, 0x47, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x07, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x2e, 0x47,
	0x65, 0x74, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x07, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x32,
	0xce, 0x03, 0x0a, 0x0d, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x49, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65,
	0x6c, 0x12, 0x1b, 0x2e, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61,
	0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x09,
	0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x12, 0x18, 0x2e, 0x70, 0x61, 0x72, 0x63,
	0x65, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x2e, 0x47, 0x65, 0x74,
	0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46,
	0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x73, 0x12, 0x1a, 0x2e,
	0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x63, 0x65,
	0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x61, 0x72, 0x63,
	0x65, 0x6c, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x12, 0x1b, 0x2e, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x49, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x72, 0x63, 0x65,
	0x6c, 0x12, 0x1b, 0x2e, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61,
	0x72, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x0f,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x42, 0x79, 0x47, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x12,
	0x1e, 0x2e, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x42, 0x79,
	0x47, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x42, 0x79,
	0x47, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x70, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x3b, 0x70, 0x61, 0x72,
	0x63, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_parcel_proto_rawDescOnce sync.Once
	file_parcel_proto_rawDescData = file_parcel_proto_rawDesc
)

func file_parcel_proto_rawDescGZIP() []byte {
	file_parcel_proto_rawDescOnce.Do(func() {
		file_parcel_proto_rawDescData = protoimpl.X.CompressGZIP(file_parcel_proto_rawDescData)
	})
	return file_parcel_proto_rawDescData
}

var file_parcel_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_parcel_proto_goTypes = []interface{}{
	(*CreateParcelRequest)(nil),     // 0: parcel.CreateParcelRequest
	(*CreateParcelResponse)(nil),    // 1: parcel.CreateParcelResponse
	(*GetParcelRequest)(nil),        // 2: parcel.GetParcelRequest
	(*GetParcelResponse)(nil),       // 3: parcel.GetParcelResponse
	(*ListParcelsRequest)(nil),      // 4: parcel.ListParcelsRequest
	(*ListParcelsResponse)(nil),     // 5: parcel.ListParcelsResponse
	(*UpdateParcelRequest)(nil),     // 6: parcel.UpdateParcelRequest
	(*UpdateParcelResponse)(nil),    // 7: parcel.UpdateParcelResponse
	(*DeleteParcelRequest)(nil),     // 8: parcel.DeleteParcelRequest
	(*DeleteParcelResponse)(nil),    // 9: parcel.DeleteParcelResponse
	(*QueryByGeometryRequest)(nil),  // 10: parcel.QueryByGeometryRequest
	(*QueryByGeometryResponse)(nil), // 11: parcel.QueryByGeometryResponse
}
var file_parcel_proto_depIdxs = []int32{
	3,  // 0: parcel.ListParcelsResponse.parcels:type_name -> parcel.GetParcelResponse
	3,  // 1: parcel.QueryByGeometryResponse.parcels:type_name -> parcel.GetParcelResponse
	0,  // 2: parcel.ParcelService.CreateParcel:input_type -> parcel.CreateParcelRequest
	2,  // 3: parcel.ParcelService.GetParcel:input_type -> parcel.GetParcelRequest
	4,  // 4: parcel.ParcelService.ListParcels:input_type -> parcel.ListParcelsRequest
	6,  // 5: parcel.ParcelService.UpdateParcel:input_type -> parcel.UpdateParcelRequest
	8,  // 6: parcel.ParcelService.DeleteParcel:input_type -> parcel.DeleteParcelRequest
	10, // 7: parcel.ParcelService.QueryByGeometry:input_type -> parcel.QueryByGeometryRequest
	1,  // 8: parcel.ParcelService.CreateParcel:output_type -> parcel.CreateParcelResponse
	3,  // 9: parcel.ParcelService.GetParcel:output_type -> parcel.GetParcelResponse
	5,  // 10: parcel.ParcelService.ListParcels:output_type -> parcel.ListParcelsResponse
	7,  // 11: parcel.ParcelService.UpdateParcel:output_type -> parcel.UpdateParcelResponse
	9,  // 12: parcel.ParcelService.DeleteParcel:output_type -> parcel.DeleteParcelResponse
	11, // 13: parcel.ParcelService.QueryByGeometry:output_type -> parcel.QueryByGeometryResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_parcel_proto_init() }
func file_parcel_proto_init() {
	if File_parcel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_parcel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateParcelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parcel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateParcelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parcel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetParcelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parcel_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetParcelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parcel_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListParcelsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parcel_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListParcelsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parcel_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateParcelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parcel_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateParcelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parcel_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteParcelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parcel_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteParcelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parcel_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryByGeometryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parcel_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryByGeometryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_parcel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_parcel_proto_goTypes,
		DependencyIndexes: file_parcel_proto_depIdxs,
		MessageInfos:      file_parcel_proto_msgTypes,
	}.Build()
	File_parcel_proto = out.File
	file_parcel_proto_rawDesc = nil
	file_parcel_proto_goTypes = nil
	file_parcel_proto_depIdxs = nil
}
