// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.5
// source: parcel.proto

package parcel

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ParcelService_CreateParcel_FullMethodName    = "/parcel.ParcelService/CreateParcel"
	ParcelService_GetParcel_FullMethodName       = "/parcel.ParcelService/GetParcel"
	ParcelService_ListParcels_FullMethodName     = "/parcel.ParcelService/ListParcels"
	ParcelService_UpdateParcel_FullMethodName    = "/parcel.ParcelService/UpdateParcel"
	ParcelService_DeleteParcel_FullMethodName    = "/parcel.ParcelService/DeleteParcel"
	ParcelService_QueryByGeometry_FullMethodName = "/parcel.ParcelService/QueryByGeometry"
)

// ParcelServiceClient is the client API for ParcelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParcelServiceClient interface {
	CreateParcel(ctx context.Context, in *CreateParcelRequest, opts ...grpc.CallOption) (*CreateParcelResponse, error)
	GetParcel(ctx context.Context, in *GetParcelRequest, opts ...grpc.CallOption) (*GetParcelResponse, error)
	ListParcels(ctx context.Context, in *ListParcelsRequest, opts ...grpc.CallOption) (*ListParcelsResponse, error)
	UpdateParcel(ctx context.Context, in *UpdateParcelRequest, opts ...grpc.CallOption) (*UpdateParcelResponse, error)
	DeleteParcel(ctx context.Context, in *DeleteParcelRequest, opts ...grpc.CallOption) (*DeleteParcelResponse, error)
	QueryByGeometry(ctx context.Context, in *QueryByGeometryRequest, opts ...grpc.CallOption) (*QueryByGeometryResponse, error)
}

type parcelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewParcelServiceClient(cc grpc.ClientConnInterface) ParcelServiceClient {
	return &parcelServiceClient{cc}
}

func (c *parcelServiceClient) CreateParcel(ctx context.Context, in *CreateParcelRequest, opts ...grpc.CallOption) (*CreateParcelResponse, error) {
	out := new(CreateParcelResponse)
	err := c.cc.Invoke(ctx, ParcelService_CreateParcel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parcelServiceClient) GetParcel(ctx context.Context, in *GetParcelRequest, opts ...grpc.CallOption) (*GetParcelResponse, error) {
	out := new(GetParcelResponse)
	err := c.cc.Invoke(ctx, ParcelService_GetParcel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parcelServiceClient) ListParcels(ctx context.Context, in *ListParcelsRequest, opts ...grpc.CallOption) (*ListParcelsResponse, error) {
	out := new(ListParcelsResponse)
	err := c.cc.Invoke(ctx, ParcelService_ListParcels_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parcelServiceClient) UpdateParcel(ctx context.Context, in *UpdateParcelRequest, opts ...grpc.CallOption) (*UpdateParcelResponse, error) {
	out := new(UpdateParcelResponse)
	err := c.cc.Invoke(ctx, ParcelService_UpdateParcel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parcelServiceClient) DeleteParcel(ctx context.Context, in *DeleteParcelRequest, opts ...grpc.CallOption) (*DeleteParcelResponse, error) {
	out := new(DeleteParcelResponse)
	err := c.cc.Invoke(ctx, ParcelService_DeleteParcel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parcelServiceClient) QueryByGeometry(ctx context.Context, in *QueryByGeometryRequest, opts ...grpc.CallOption) (*QueryByGeometryResponse, error) {
	out := new(QueryByGeometryResponse)
	err := c.cc.Invoke(ctx, ParcelService_QueryByGeometry_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParcelServiceServer is the server API for ParcelService service.
// All implementations must embed UnimplementedParcelServiceServer
// for forward compatibility
type ParcelServiceServer interface {
	CreateParcel(context.Context, *CreateParcelRequest) (*CreateParcelResponse, error)
	GetParcel(context.Context, *GetParcelRequest) (*GetParcelResponse, error)
	ListParcels(context.Context, *ListParcelsRequest) (*ListParcelsResponse, error)
	UpdateParcel(context.Context, *UpdateParcelRequest) (*UpdateParcelResponse, error)
	DeleteParcel(context.Context, *DeleteParcelRequest) (*DeleteParcelResponse, error)
	QueryByGeometry(context.Context, *QueryByGeometryRequest) (*QueryByGeometryResponse, error)
	mustEmbedUnimplementedParcelServiceServer()
}

// UnimplementedParcelServiceServer must be embedded to have forward compatible implementations.
type UnimplementedParcelServiceServer struct {
}

func (UnimplementedParcelServiceServer) CreateParcel(context.Context, *CreateParcelRequest) (*CreateParcelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateParcel not implemented")
}
func (UnimplementedParcelServiceServer) GetParcel(context.Context, *GetParcelRequest) (*GetParcelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParcel not implemented")
}
func (UnimplementedParcelServiceServer) ListParcels(context.Context, *ListParcelsRequest) (*ListParcelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListParcels not implemented")
}
func (UnimplementedParcelServiceServer) UpdateParcel(context.Context, *UpdateParcelRequest) (*UpdateParcelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParcel not implemented")
}
func (UnimplementedParcelServiceServer) DeleteParcel(context.Context, *DeleteParcelRequest) (*DeleteParcelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteParcel not implemented")
}
func (UnimplementedParcelServiceServer) QueryByGeometry(context.Context, *QueryByGeometryRequest) (*QueryByGeometryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryByGeometry not implemented")
}
func (UnimplementedParcelServiceServer) mustEmbedUnimplementedParcelServiceServer() {}

// UnsafeParcelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParcelServiceServer will
// result in compilation errors.
type UnsafeParcelServiceServer interface {
	mustEmbedUnimplementedParcelServiceServer()
}

func RegisterParcelServiceServer(s grpc.ServiceRegistrar, srv ParcelServiceServer) {
	s.RegisterService(&ParcelService_ServiceDesc, srv)
}

func _ParcelService_CreateParcel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateParcelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParcelServiceServer).CreateParcel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParcelService_CreateParcel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParcelServiceServer).CreateParcel(ctx, req.(*CreateParcelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParcelService_GetParcel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParcelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParcelServiceServer).GetParcel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParcelService_GetParcel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParcelServiceServer).GetParcel(ctx, req.(*GetParcelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParcelService_ListParcels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListParcelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParcelServiceServer).ListParcels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParcelService_ListParcels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParcelServiceServer).ListParcels(ctx, req.(*ListParcelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParcelService_UpdateParcel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateParcelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParcelServiceServer).UpdateParcel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParcelService_UpdateParcel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParcelServiceServer).UpdateParcel(ctx, req.(*UpdateParcelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParcelService_DeleteParcel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteParcelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParcelServiceServer).DeleteParcel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParcelService_DeleteParcel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParcelServiceServer).DeleteParcel(ctx, req.(*DeleteParcelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParcelService_QueryByGeometry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryByGeometryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParcelServiceServer).QueryByGeometry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParcelService_QueryByGeometry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParcelServiceServer).QueryByGeometry(ctx, req.(*QueryByGeometryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ParcelService_ServiceDesc is the grpc.ServiceDesc for ParcelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParcelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parcel.ParcelService",
	HandlerType: (*ParcelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateParcel",
			Handler:    _ParcelService_CreateParcel_Handler,
		},
		{
			MethodName: "GetParcel",
			Handler:    _ParcelService_GetParcel_Handler,
		},
		{
			MethodName: "ListParcels",
			Handler:    _ParcelService_ListParcels_Handler,
		},
		{
			MethodName: "UpdateParcel",
			Handler:    _ParcelService_UpdateParcel_Handler,
		},
		{
			MethodName: "DeleteParcel",
			Handler:    _ParcelService_DeleteParcel_Handler,
		},
		{
			MethodName: "QueryByGeometry",
			Handler:    _ParcelService_QueryByGeometry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "parcel.proto",
}
