// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Report struct {
	ID          int64              `json:"id"`
	ProducerID  int64              `json:"producer_id"`
	ReportType  string             `json:"report_type"`
	Url         pgtype.Text        `json:"url"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
