// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	// Report queries
	CreateReport(ctx context.Context, arg CreateReportParams) (Report, error)
	GetReport(ctx context.Context, id int64) (Report, error)
	ListReports(ctx context.Context, arg ListReportsParams) ([]Report, error)
}

var _ Querier = (*Queries)(nil)
