// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :one

INSERT INTO reports (producer_id, report_type, url)
VALUES ($1, $2, $3)
RETURNING id, producer_id, report_type, url, generated_at, created_at
`

type CreateReportParams struct {
	ProducerID int64       `json:"producer_id"`
	ReportType string      `json:"report_type"`
	Url        pgtype.Text `json:"url"`
}

// Report queries
func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport, arg.ProducerID, arg.ReportType, arg.Url)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ProducerID,
		&i.ReportType,
		&i.Url,
		&i.GeneratedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getReport = `-- name: GetReport :one
SELECT id, producer_id, report_type, url, generated_at, created_at
FROM reports WHERE id = $1
`

func (q *Queries) GetReport(ctx context.Context, id int64) (Report, error) {
	row := q.db.QueryRow(ctx, getReport, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ProducerID,
		&i.ReportType,
		&i.Url,
		&i.GeneratedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listReports = `-- name: ListReports :many
SELECT id, producer_id, report_type, url, generated_at, created_at
FROM reports WHERE producer_id = $1
ORDER BY generated_at DESC
LIMIT $2 OFFSET $3
`

type ListReportsParams struct {
	ProducerID int64 `json:"producer_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListReports(ctx context.Context, arg ListReportsParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReports, arg.ProducerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ProducerID,
			&i.ReportType,
			&i.Url,
			&i.GeneratedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
