// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Notification struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"user_id"`
	NotificationType string             `json:"notification_type"`
	Channel          string             `json:"channel"`
	Title            pgtype.Text        `json:"title"`
	Message          string             `json:"message"`
	Metadata         []byte             `json:"metadata"`
	Read             bool               `json:"read"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}
