// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one

INSERT INTO notifications (user_id, notification_type, channel, title, message, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, notification_type, channel, title, message, read, created_at
`

type CreateNotificationParams struct {
	UserID           int64       `json:"user_id"`
	NotificationType string      `json:"notification_type"`
	Channel          string      `json:"channel"`
	Title            pgtype.Text `json:"title"`
	Message          string      `json:"message"`
	Metadata         []byte      `json:"metadata"`
}

type CreateNotificationRow struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"user_id"`
	NotificationType string             `json:"notification_type"`
	Channel          string             `json:"channel"`
	Title            pgtype.Text        `json:"title"`
	Message          string             `json:"message"`
	Read             bool               `json:"read"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

// Notification queries
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (CreateNotificationRow, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.NotificationType,
		arg.Channel,
		arg.Title,
		arg.Message,
		arg.Metadata,
	)
	var i CreateNotificationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NotificationType,
		&i.Channel,
		&i.Title,
		&i.Message,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const getNotification = `-- name: GetNotification :one
SELECT id, user_id, notification_type, channel, title, message, read, created_at
FROM notifications WHERE id = $1
`

type GetNotificationRow struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"user_id"`
	NotificationType string             `json:"notification_type"`
	Channel          string             `json:"channel"`
	Title            pgtype.Text        `json:"title"`
	Message          string             `json:"message"`
	Read             bool               `json:"read"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetNotification(ctx context.Context, id int64) (GetNotificationRow, error) {
	row := q.db.QueryRow(ctx, getNotification, id)
	var i GetNotificationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NotificationType,
		&i.Channel,
		&i.Title,
		&i.Message,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, notification_type, channel, title, message, read, created_at
FROM notifications WHERE user_id = $1 AND ($2::boolean = FALSE OR read = FALSE)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListNotificationsParams struct {
	UserID  int64 `json:"user_id"`
	Column2 bool  `json:"column_2"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

type ListNotificationsRow struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"user_id"`
	NotificationType string             `json:"notification_type"`
	Channel          string             `json:"channel"`
	Title            pgtype.Text        `json:"title"`
	Message          string             `json:"message"`
	Read             bool               `json:"read"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsRow
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NotificationType,
			&i.Channel,
			&i.Title,
			&i.Message,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAsRead = `-- name: MarkAsRead :exec
UPDATE notifications SET read = TRUE WHERE id = $1
`

func (q *Queries) MarkAsRead(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markAsRead, id)
	return err
}
