// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	// Notification queries
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (CreateNotificationRow, error)
	GetNotification(ctx context.Context, id int64) (GetNotificationRow, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error)
	MarkAsRead(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
