// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.5
// source: production.proto

package production

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ProductionService_RecordActivity_FullMethodName = "/production.ProductionService/RecordActivity"
	ProductionService_GetActivity_FullMethodName    = "/production.ProductionService/GetActivity"
	ProductionService_ListActivities_FullMethodName = "/production.ProductionService/ListActivities"
)

// ProductionServiceClient is the client API for ProductionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductionServiceClient interface {
	RecordActivity(ctx context.Context, in *RecordActivityRequest, opts ...grpc.CallOption) (*RecordActivityResponse, error)
	GetActivity(ctx context.Context, in *GetActivityRequest, opts ...grpc.CallOption) (*GetActivityResponse, error)
	ListActivities(ctx context.Context, in *ListActivitiesRequest, opts ...grpc.CallOption) (*ListActivitiesResponse, error)
}

type productionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductionServiceClient(cc grpc.ClientConnInterface) ProductionServiceClient {
	return &productionServiceClient{cc}
}

func (c *productionServiceClient) RecordActivity(ctx context.Context, in *RecordActivityRequest, opts ...grpc.CallOption) (*RecordActivityResponse, error) {
	out := new(RecordActivityResponse)
	err := c.cc.Invoke(ctx, ProductionService_RecordActivity_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionServiceClient) GetActivity(ctx context.Context, in *GetActivityRequest, opts ...grpc.CallOption) (*GetActivityResponse, error) {
	out := new(GetActivityResponse)
	err := c.cc.Invoke(ctx, ProductionService_GetActivity_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionServiceClient) ListActivities(ctx context.Context, in *ListActivitiesRequest, opts ...grpc.CallOption) (*ListActivitiesResponse, error) {
	out := new(ListActivitiesResponse)
	err := c.cc.Invoke(ctx, ProductionService_ListActivities_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductionServiceServer is the server API for ProductionService service.
// All implementations must embed UnimplementedProductionServiceServer
// for forward compatibility
type ProductionServiceServer interface {
	RecordActivity(context.Context, *RecordActivityRequest) (*RecordActivityResponse, error)
	GetActivity(context.Context, *GetActivityRequest) (*GetActivityResponse, error)
	ListActivities(context.Context, *ListActivitiesRequest) (*ListActivitiesResponse, error)
	mustEmbedUnimplementedProductionServiceServer()
}

// UnimplementedProductionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProductionServiceServer struct {
}

func (UnimplementedProductionServiceServer) RecordActivity(context.Context, *RecordActivityRequest) (*RecordActivityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordActivity not implemented")
}
func (UnimplementedProductionServiceServer) GetActivity(context.Context, *GetActivityRequest) (*GetActivityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActivity not implemented")
}
func (UnimplementedProductionServiceServer) ListActivities(context.Context, *ListActivitiesRequest) (*ListActivitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListActivities not implemented")
}
func (UnimplementedProductionServiceServer) mustEmbedUnimplementedProductionServiceServer() {}

// UnsafeProductionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductionServiceServer will
// result in compilation errors.
type UnsafeProductionServiceServer interface {
	mustEmbedUnimplementedProductionServiceServer()
}

func RegisterProductionServiceServer(s grpc.ServiceRegistrar, srv ProductionServiceServer) {
	s.RegisterService(&ProductionService_ServiceDesc, srv)
}

func _ProductionService_RecordActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServiceServer).RecordActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductionService_RecordActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServiceServer).RecordActivity(ctx, req.(*RecordActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductionService_GetActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServiceServer).GetActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductionService_GetActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServiceServer).GetActivity(ctx, req.(*GetActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductionService_ListActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActivitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServiceServer).ListActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductionService_ListActivities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServiceServer).ListActivities(ctx, req.(*ListActivitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductionService_ServiceDesc is the grpc.ServiceDesc for ProductionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "production.ProductionService",
	HandlerType: (*ProductionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordActivity",
			Handler:    _ProductionService_RecordActivity_Handler,
		},
		{
			MethodName: "GetActivity",
			Handler:    _ProductionService_GetActivity_Handler,
		},
		{
			MethodName: "ListActivities",
			Handler:    _ProductionService_ListActivities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "production.proto",
}
