// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	// User queries
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateUserRole(ctx context.Context, arg CreateUserRoleParams) error
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	GetUserByToken(ctx context.Context, tokenHash string) (GetUserByTokenRow, error)
	GetUserRoles(ctx context.Context, userID int64) ([]string, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpsertToken(ctx context.Context, arg UpsertTokenParams) error
}

var _ Querier = (*Queries)(nil)
