// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.5
// source: producer.proto

package producer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ProducerService_CreateProducer_FullMethodName = "/producer.ProducerService/CreateProducer"
	ProducerService_GetProducer_FullMethodName    = "/producer.ProducerService/GetProducer"
	ProducerService_ListProducers_FullMethodName  = "/producer.ProducerService/ListProducers"
	ProducerService_UpdateProducer_FullMethodName = "/producer.ProducerService/UpdateProducer"
	ProducerService_DeleteProducer_FullMethodName = "/producer.ProducerService/DeleteProducer"
)

// ProducerServiceClient is the client API for ProducerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProducerServiceClient interface {
	CreateProducer(ctx context.Context, in *CreateProducerRequest, opts ...grpc.CallOption) (*CreateProducerResponse, error)
	GetProducer(ctx context.Context, in *GetProducerRequest, opts ...grpc.CallOption) (*GetProducerResponse, error)
	ListProducers(ctx context.Context, in *ListProducersRequest, opts ...grpc.CallOption) (*ListProducersResponse, error)
	UpdateProducer(ctx context.Context, in *UpdateProducerRequest, opts ...grpc.CallOption) (*UpdateProducerResponse, error)
	DeleteProducer(ctx context.Context, in *DeleteProducerRequest, opts ...grpc.CallOption) (*DeleteProducerResponse, error)
}

type producerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProducerServiceClient(cc grpc.ClientConnInterface) ProducerServiceClient {
	return &producerServiceClient{cc}
}

func (c *producerServiceClient) CreateProducer(ctx context.Context, in *CreateProducerRequest, opts ...grpc.CallOption) (*CreateProducerResponse, error) {
	out := new(CreateProducerResponse)
	err := c.cc.Invoke(ctx, ProducerService_CreateProducer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producerServiceClient) GetProducer(ctx context.Context, in *GetProducerRequest, opts ...grpc.CallOption) (*GetProducerResponse, error) {
	out := new(GetProducerResponse)
	err := c.cc.Invoke(ctx, ProducerService_GetProducer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producerServiceClient) ListProducers(ctx context.Context, in *ListProducersRequest, opts ...grpc.CallOption) (*ListProducersResponse, error) {
	out := new(ListProducersResponse)
	err := c.cc.Invoke(ctx, ProducerService_ListProducers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producerServiceClient) UpdateProducer(ctx context.Context, in *UpdateProducerRequest, opts ...grpc.CallOption) (*UpdateProducerResponse, error) {
	out := new(UpdateProducerResponse)
	err := c.cc.Invoke(ctx, ProducerService_UpdateProducer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producerServiceClient) DeleteProducer(ctx context.Context, in *DeleteProducerRequest, opts ...grpc.CallOption) (*DeleteProducerResponse, error) {
	out := new(DeleteProducerResponse)
	err := c.cc.Invoke(ctx, ProducerService_DeleteProducer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProducerServiceServer is the server API for ProducerService service.
// All implementations must embed UnimplementedProducerServiceServer
// for forward compatibility
type ProducerServiceServer interface {
	CreateProducer(context.Context, *CreateProducerRequest) (*CreateProducerResponse, error)
	GetProducer(context.Context, *GetProducerRequest) (*GetProducerResponse, error)
	ListProducers(context.Context, *ListProducersRequest) (*ListProducersResponse, error)
	UpdateProducer(context.Context, *UpdateProducerRequest) (*UpdateProducerResponse, error)
	DeleteProducer(context.Context, *DeleteProducerRequest) (*DeleteProducerResponse, error)
	mustEmbedUnimplementedProducerServiceServer()
}

// UnimplementedProducerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProducerServiceServer struct {
}

func (UnimplementedProducerServiceServer) CreateProducer(context.Context, *CreateProducerRequest) (*CreateProducerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProducer not implemented")
}
func (UnimplementedProducerServiceServer) GetProducer(context.Context, *GetProducerRequest) (*GetProducerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProducer not implemented")
}
func (UnimplementedProducerServiceServer) ListProducers(context.Context, *ListProducersRequest) (*ListProducersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProducers not implemented")
}
func (UnimplementedProducerServiceServer) UpdateProducer(context.Context, *UpdateProducerRequest) (*UpdateProducerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProducer not implemented")
}
func (UnimplementedProducerServiceServer) DeleteProducer(context.Context, *DeleteProducerRequest) (*DeleteProducerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProducer not implemented")
}
func (UnimplementedProducerServiceServer) mustEmbedUnimplementedProducerServiceServer() {}

// UnsafeProducerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProducerServiceServer will
// result in compilation errors.
type UnsafeProducerServiceServer interface {
	mustEmbedUnimplementedProducerServiceServer()
}

func RegisterProducerServiceServer(s grpc.ServiceRegistrar, srv ProducerServiceServer) {
	s.RegisterService(&ProducerService_ServiceDesc, srv)
}

func _ProducerService_CreateProducer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProducerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerServiceServer).CreateProducer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProducerService_CreateProducer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerServiceServer).CreateProducer(ctx, req.(*CreateProducerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProducerService_GetProducer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProducerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerServiceServer).GetProducer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProducerService_GetProducer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerServiceServer).GetProducer(ctx, req.(*GetProducerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProducerService_ListProducers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProducersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerServiceServer).ListProducers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProducerService_ListProducers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerServiceServer).ListProducers(ctx, req.(*ListProducersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProducerService_UpdateProducer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProducerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerServiceServer).UpdateProducer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProducerService_UpdateProducer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerServiceServer).UpdateProducer(ctx, req.(*UpdateProducerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProducerService_DeleteProducer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProducerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerServiceServer).DeleteProducer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProducerService_DeleteProducer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerServiceServer).DeleteProducer(ctx, req.(*DeleteProducerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProducerService_ServiceDesc is the grpc.ServiceDesc for ProducerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProducerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "producer.ProducerService",
	HandlerType: (*ProducerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProducer",
			Handler:    _ProducerService_CreateProducer_Handler,
		},
		{
			MethodName: "GetProducer",
			Handler:    _ProducerService_GetProducer_Handler,
		},
		{
			MethodName: "ListProducers",
			Handler:    _ProducerService_ListProducers_Handler,
		},
		{
			MethodName: "UpdateProducer",
			Handler:    _ProducerService_UpdateProducer_Handler,
		},
		{
			MethodName: "DeleteProducer",
			Handler:    _ProducerService_DeleteProducer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "producer.proto",
}
