// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activities.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActivity = `-- name: GetActivity :one
SELECT id, parcel_id, activity_type, description, timestamp
FROM production_activities WHERE id = $1
`

type GetActivityRow struct {
	ID           int64              `json:"id"`
	ParcelID     int64              `json:"parcel_id"`
	ActivityType string             `json:"activity_type"`
	Description  pgtype.Text        `json:"description"`
	Timestamp    pgtype.Timestamptz `json:"timestamp"`
}

func (q *Queries) GetActivity(ctx context.Context, id int64) (GetActivityRow, error) {
	row := q.db.QueryRow(ctx, getActivity, id)
	var i GetActivityRow
	err := row.Scan(
		&i.ID,
		&i.ParcelID,
		&i.ActivityType,
		&i.Description,
		&i.Timestamp,
	)
	return i, err
}

const listActivities = `-- name: ListActivities :many
SELECT id, parcel_id, activity_type, description, timestamp
FROM production_activities WHERE parcel_id = $1
ORDER BY timestamp DESC
LIMIT $2 OFFSET $3
`

type ListActivitiesParams struct {
	ParcelID int64 `json:"parcel_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

type ListActivitiesRow struct {
	ID           int64              `json:"id"`
	ParcelID     int64              `json:"parcel_id"`
	ActivityType string             `json:"activity_type"`
	Description  pgtype.Text        `json:"description"`
	Timestamp    pgtype.Timestamptz `json:"timestamp"`
}

func (q *Queries) ListActivities(ctx context.Context, arg ListActivitiesParams) ([]ListActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listActivities, arg.ParcelID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivitiesRow
	for rows.Next() {
		var i ListActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.ParcelID,
			&i.ActivityType,
			&i.Description,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordActivity = `-- name: RecordActivity :one

INSERT INTO production_activities (parcel_id, activity_type, description, timestamp, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, parcel_id, activity_type, description, timestamp
`

type RecordActivityParams struct {
	ParcelID     int64              `json:"parcel_id"`
	ActivityType string             `json:"activity_type"`
	Description  pgtype.Text        `json:"description"`
	Timestamp    pgtype.Timestamptz `json:"timestamp"`
	Metadata     []byte             `json:"metadata"`
}

type RecordActivityRow struct {
	ID           int64              `json:"id"`
	ParcelID     int64              `json:"parcel_id"`
	ActivityType string             `json:"activity_type"`
	Description  pgtype.Text        `json:"description"`
	Timestamp    pgtype.Timestamptz `json:"timestamp"`
}

// Production queries
func (q *Queries) RecordActivity(ctx context.Context, arg RecordActivityParams) (RecordActivityRow, error) {
	row := q.db.QueryRow(ctx, recordActivity,
		arg.ParcelID,
		arg.ActivityType,
		arg.Description,
		arg.Timestamp,
		arg.Metadata,
	)
	var i RecordActivityRow
	err := row.Scan(
		&i.ID,
		&i.ParcelID,
		&i.ActivityType,
		&i.Description,
		&i.Timestamp,
	)
	return i, err
}
