// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ProductionActivity struct {
	ID           int64              `json:"id"`
	ParcelID     int64              `json:"parcel_id"`
	ActivityType string             `json:"activity_type"`
	Description  pgtype.Text        `json:"description"`
	Timestamp    pgtype.Timestamptz `json:"timestamp"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
