// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetActivity(ctx context.Context, id int64) (GetActivityRow, error)
	ListActivities(ctx context.Context, arg ListActivitiesParams) ([]ListActivitiesRow, error)
	// Production queries
	RecordActivity(ctx context.Context, arg RecordActivityParams) (RecordActivityRow, error)
}

var _ Querier = (*Queries)(nil)
