// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Parcel struct {
	ID           int64              `json:"id"`
	ProducerID   int64              `json:"producer_id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	Geometry     interface{}        `json:"geometry"`
	AreaHectares pgtype.Numeric     `json:"area_hectares"`
	CropType     pgtype.Text        `json:"crop_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
