// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: parcels.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createParcel = `-- name: CreateParcel :one

INSERT INTO parcels (producer_id, name, description, geometry, area_hectares, crop_type)
VALUES ($1, $2, $3, ST_GeomFromText($4, 4326), $5, $6)
RETURNING id, producer_id, name, description, ST_AsText(geometry) as geometry, area_hectares, crop_type, created_at
`

type CreateParcelParams struct {
	ProducerID     int64          `json:"producer_id"`
	Name           string         `json:"name"`
	Description    pgtype.Text    `json:"description"`
	StGeomfromtext interface{}    `json:"st_geomfromtext"`
	AreaHectares   pgtype.Numeric `json:"area_hectares"`
	CropType       pgtype.Text    `json:"crop_type"`
}

type CreateParcelRow struct {
	ID           int64              `json:"id"`
	ProducerID   int64              `json:"producer_id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	Geometry     interface{}        `json:"geometry"`
	AreaHectares pgtype.Numeric     `json:"area_hectares"`
	CropType     pgtype.Text        `json:"crop_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// Parcel queries
func (q *Queries) CreateParcel(ctx context.Context, arg CreateParcelParams) (CreateParcelRow, error) {
	row := q.db.QueryRow(ctx, createParcel,
		arg.ProducerID,
		arg.Name,
		arg.Description,
		arg.StGeomfromtext,
		arg.AreaHectares,
		arg.CropType,
	)
	var i CreateParcelRow
	err := row.Scan(
		&i.ID,
		&i.ProducerID,
		&i.Name,
		&i.Description,
		&i.Geometry,
		&i.AreaHectares,
		&i.CropType,
		&i.CreatedAt,
	)
	return i, err
}

const deleteParcel = `-- name: DeleteParcel :exec
DELETE FROM parcels WHERE id = $1
`

func (q *Queries) DeleteParcel(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteParcel, id)
	return err
}

const getParcel = `-- name: GetParcel :one
SELECT id, producer_id, name, description, ST_AsText(geometry) as geometry, area_hectares, crop_type, created_at
FROM parcels WHERE id = $1
`

type GetParcelRow struct {
	ID           int64              `json:"id"`
	ProducerID   int64              `json:"producer_id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	Geometry     interface{}        `json:"geometry"`
	AreaHectares pgtype.Numeric     `json:"area_hectares"`
	CropType     pgtype.Text        `json:"crop_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetParcel(ctx context.Context, id int64) (GetParcelRow, error) {
	row := q.db.QueryRow(ctx, getParcel, id)
	var i GetParcelRow
	err := row.Scan(
		&i.ID,
		&i.ProducerID,
		&i.Name,
		&i.Description,
		&i.Geometry,
		&i.AreaHectares,
		&i.CropType,
		&i.CreatedAt,
	)
	return i, err
}

const getParcelCount = `-- name: GetParcelCount :one
SELECT COUNT(*) FROM parcels WHERE producer_id = $1
`

func (q *Queries) GetParcelCount(ctx context.Context, producerID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getParcelCount, producerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listParcels = `-- name: ListParcels :many
SELECT id, producer_id, name, description, ST_AsText(geometry) as geometry, area_hectares, crop_type, created_at
FROM parcels WHERE producer_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListParcelsParams struct {
	ProducerID int64 `json:"producer_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

type ListParcelsRow struct {
	ID           int64              `json:"id"`
	ProducerID   int64              `json:"producer_id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	Geometry     interface{}        `json:"geometry"`
	AreaHectares pgtype.Numeric     `json:"area_hectares"`
	CropType     pgtype.Text        `json:"crop_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListParcels(ctx context.Context, arg ListParcelsParams) ([]ListParcelsRow, error) {
	rows, err := q.db.Query(ctx, listParcels, arg.ProducerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParcelsRow
	for rows.Next() {
		var i ListParcelsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProducerID,
			&i.Name,
			&i.Description,
			&i.Geometry,
			&i.AreaHectares,
			&i.CropType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryByGeometry = `-- name: QueryByGeometry :many
SELECT id, producer_id, name, description, ST_AsText(geometry) as geometry, area_hectares, crop_type, created_at
FROM parcels
WHERE ST_Intersects(geometry, ST_GeomFromText($1, 4326))
ORDER BY created_at DESC
`

type QueryByGeometryRow struct {
	ID           int64              `json:"id"`
	ProducerID   int64              `json:"producer_id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	Geometry     interface{}        `json:"geometry"`
	AreaHectares pgtype.Numeric     `json:"area_hectares"`
	CropType     pgtype.Text        `json:"crop_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) QueryByGeometry(ctx context.Context, stGeomfromtext interface{}) ([]QueryByGeometryRow, error) {
	rows, err := q.db.Query(ctx, queryByGeometry, stGeomfromtext)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryByGeometryRow
	for rows.Next() {
		var i QueryByGeometryRow
		if err := rows.Scan(
			&i.ID,
			&i.ProducerID,
			&i.Name,
			&i.Description,
			&i.Geometry,
			&i.AreaHectares,
			&i.CropType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateParcel = `-- name: UpdateParcel :exec
UPDATE parcels
SET name = $2, description = $3, crop_type = $4, geometry = ST_GeomFromText($5, 4326), updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateParcelParams struct {
	ID             int64       `json:"id"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	CropType       pgtype.Text `json:"crop_type"`
	StGeomfromtext interface{} `json:"st_geomfromtext"`
}

func (q *Queries) UpdateParcel(ctx context.Context, arg UpdateParcelParams) error {
	_, err := q.db.Exec(ctx, updateParcel,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CropType,
		arg.StGeomfromtext,
	)
	return err
}
