// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	// Parcel queries
	CreateParcel(ctx context.Context, arg CreateParcelParams) (CreateParcelRow, error)
	DeleteParcel(ctx context.Context, id int64) error
	GetParcel(ctx context.Context, id int64) (GetParcelRow, error)
	GetParcelCount(ctx context.Context, producerID int64) (int64, error)
	ListParcels(ctx context.Context, arg ListParcelsParams) ([]ListParcelsRow, error)
	QueryByGeometry(ctx context.Context, stGeomfromtext interface{}) ([]QueryByGeometryRow, error)
	UpdateParcel(ctx context.Context, arg UpdateParcelParams) error
}

var _ Querier = (*Queries)(nil)
