name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build Alert Service
      run: cd services/alert-service && go build -v ./cmd/server/...

    - name: Build Notification Service
      run: cd services/notification-service && go build -v ./cmd/server/...

    - name: Build Parcel Service
      run: cd services/parcel-service && go build -v ./cmd/server/...

    - name: Build Producer Service
      run: cd services/producer-service && go build -v ./cmd/server/...

    - name: Build Production Service
      run: cd services/production-service && go build -v ./cmd/server/...

    - name: Build Report Service
      run: cd services/report-service && go build -v ./cmd/server/...

    - name: Build User Service
      run: cd services/user-service && go build -v ./cmd/server/...

    - name: Build All Services
      run: make build
